##
## Makefile for corewar in /u/all/cerisi_m/cu/rendu/corewar
## 
## Made by mickael cerisier
## Login   <cerisi_m@epitech.net>
## 
## Started on  Sun Feb 28 19:31:28 2010 mickael cerisier
## Last update Wed Mar  3 18:13:42 2010 mickael cerisier
##

all	:
	$(MAKE) -C my_lib $(NAME)
	$(MAKE) -C my_printf $(NAME)

clean	:
	$(MAKE) -C my_lib clean
	$(MAKE) -C my_printf clean

fclean	:
	$(MAKE) -C my_lib fclean
	$(MAKE) -C my_printf fclean

re	:
	$(MAKE) -C my_lib re
	$(MAKE) -C my_printf re
